# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  PUBLISH_DIR: publish
  PUBLISH_NO_PDB: -p:DebugType=None -p:DebugSymbols=false
  PUBLISH_CONFIGURATION: Release

tasks:
  default:
    cmds:
      - task --list
    silent: true

  restore:
    desc: Restore project dependencies
    cmds:
      - dotnet restore

  build_debug:
    desc: Build the project in Debug mode
    cmds:
      - dotnet build -c Debug --no-restore

  build_release:
    desc: Build the project in Release mode
    cmds:
      - dotnet build -c Release --no-restore

  build:
    desc: Build the project
    cmds:
      - task: build_debug
      - task: build_release

  publish_linux:
    desc: Publish the project for Linux
    dir: ./Novugit
    cmds:
      - dotnet publish --no-restore -c {{.PUBLISH_CONFIGURATION}} -r linux-x64 {{.PUBLISH_NO_PDB}} -o ../{{.PUBLISH_DIR}}/linux 
      
  publish_windows:
    desc: Publish the project for Windows
    dir: ./Novugit
    cmds:
      - dotnet publish --no-restore -c {{.PUBLISH_CONFIGURATION}} -r win-x64 {{.PUBLISH_NO_PDB}} -o ../{{.PUBLISH_DIR}}/windows
        
  publish_macos:
    desc: Publish the project for MacOS
    dir: ./Novugit
    cmds:
      - dotnet publish --no-restore -c {{.PUBLISH_CONFIGURATION}} -r osx-x64 {{.PUBLISH_NO_PDB}} -o ../{{.PUBLISH_DIR}}/macosx_x64
      - dotnet publish --no-restore -c {{.PUBLISH_CONFIGURATION}} -r osx-arm64 {{.PUBLISH_NO_PDB}} -o ../{{.PUBLISH_DIR}}/macos_arm64
  
  publish:
    desc: Publish the project for all platforms
    cmds:
      - task: publish_linux
      - task: publish_windows
      - task: publish_macos
        
  clean:
    desc: Clean the project
    cmds:
      - dotnet clean -c Debug
      - dotnet clean -c Release
      - rm -rf {{.PUBLISH_DIR}}
        
  git_clean:
    desc: Clean untracked files from the repository
    cmds:
      - git clean -fdx
  
  git_reset:
    desc: Reset the repository to the last commit
    cmds:
      - git reset --hard HEAD
        
  full_build:
    desc: Perform a full clean, restore, build, and publish
    cmds:
      - task: clean
      - task: restore
      - task: build
      - task: publish