# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true

  restore:
    desc: Restore project dependencies
    cmds:
      - dotnet restore

  build_debug:
    desc: Build the project in Debug mode
    cmds:
      - dotnet build --configuration Debug

  build_release:
    desc: Build the project in Release mode
    cmds:
      - dotnet build --configuration Release

  build:
    desc: Build the project
    cmds:
      - task: build_debug
      - task: build_release

  publish_linux:
    desc: Publish the project for Linux
    dir: ./Novugit
    cmds:
      - dotnet publish --configuration Release --runtime linux-x64 --output ../publish/linux
      
  publish_windows:
    desc: Publish the project for Windows
    dir: ./Novugit
    cmds:
      - dotnet publish --configuration Release --runtime win-x64 --output ../publish/windows
        
  publish_macos:
    desc: Publish the project for MacOS
    dir: ./Novugit
    cmds:
      - dotnet publish --configuration Release --runtime osx-x64 --output ../publish/macosx
  
  publish:
    desc: Publish the project for all platforms
    cmds:
      - task: publish_linux
      - task: publish_windows
      - task: publish_macos